In [16]:
#Lais Nicolau dos Anjos - 231022361
# Grupo 2 Trabalho : Limpeza do dataset Distribution of enrolled students, new entrants and graduates by field of education
#Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display

In [44]:
df = pd.DataFrame(pd.read_csv('/content/OECD.EDU.IMEP,DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_NF_DIST_FIELD,1.0+.ISCED11_5T8+ISCED11_5+ISCED11_6+ISCED11_7+ISCED11_8.GRAD...F00+F01+F02+F03+F04+F05+F06+F07+F08+F09+F10+_TX_U..A...._T.._T..csv'))
df

,STRUCTURE,STRUCTURE_ID,STRUCTURE_NAME,ACTION,REF_AREA,Reference area,EDUCATION_LEV,Education level,MEASURE,Measure,...,CONF_STATUS,Confidentiality status,COMMENT_OBS,Observation comment,DECIMALS,Decimals,TIME_PER_COLLECT,Time period collection,UNIT_MULT,Unit multiplier
0,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,JPN,Japan,ISCED11_5,Short-cycle tertiary education,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
1,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,JPN,Japan,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
2,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,JPN,Japan,ISCED11_7,Master’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
3,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,JPN,Japan,ISCED11_8,Doctoral or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
4,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,JPN,Japan,ISCED11_5T8,Tertiary education,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2695,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,ROU,Romania,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
2696,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,ROU,Romania,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
2697,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,ROU,Romania,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
2698,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,ROU,Romania,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units
2699,DATAFLOW,OECD.EDU.IMEP:DSD_EAG_UOE_NON_FIN_STUD@DF_UOE_...,"Distribution of enrolled students, new entrant...",I,ROU,Romania,ISCED11_6,Bachelor’s or equivalent level,GRAD,Graduates,...,NaN,NaN,NaN,NaN,2,Two,NaN,NaN,0,Units

In [45]:
df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION', 'REF_AREA',
       'Reference area', 'EDUCATION_LEV', 'Education level', 'MEASURE',
       'Measure', 'EDUCATION_TYPE', 'Education type', 'INTENSITY', 'Intensity',
       'EDUCATION_FIELD', 'Field of education', 'GRADE', 'Grade', 'FREQ',
       'Frequency of observation', 'ORIGIN', 'Origin', 'DESTINATION',
       'Destination', 'INST_TYPE_EDU', 'Type of educational institution',
       'MOBILITY', 'Mobility', 'UNIT_MEASURE', 'Unit of measure', 'SEX', 'Sex',
       'AGE', 'Age', 'TIME_PERIOD', 'Time period', 'OBS_VALUE',
       'Observation value', 'REF_YEAR_AGES', 'Reference date for ages',
       'ORIGIN_CRITERION', 'Origin criterion', 'REPYEARSTART',
       'Reference year start', 'REPYEAREND', 'Reference year end',
       'OBS_STATUS', 'Observation status', 'CONF_STATUS',
       'Confidentiality status', 'COMMENT_OBS', 'Observation comment',
       'DECIMALS', 'Decimals', 'TIME_PER_COLLECT', 'Time period collection',
       'UNIT_MULT', 'Unit multiplier'],
      dtype='object')

-> Há várias colunas duplicadas, que contém os mesmos dados porém com outros nomes.
Exemplo:

In [49]:
df[['MEASURE', 'Measure']]

     MEASURE    Measure
0       GRAD  Graduates
1       GRAD  Graduates
2       GRAD  Graduates
3       GRAD  Graduates
4       GRAD  Graduates
...      ...        ...
2695    GRAD  Graduates
2696    GRAD  Graduates
2697    GRAD  Graduates
2698    GRAD  Graduates
2699    GRAD  Graduates

[2700 rows x 2 columns]

In [56]:
df_limpo = df.drop(columns=[df.columns[i] for i in range(4, len(df.columns)) if i % 2 == 0])
df_limpo.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION',
       'Reference area', 'Education level', 'Measure', 'Education type',
       'Intensity', 'Field of education', 'Grade', 'Frequency of observation',
       'Origin', 'Destination', 'Type of educational institution', 'Mobility',
       'Unit of measure', 'Sex', 'Age', 'Time period', 'Observation value',
       'Reference date for ages', 'Origin criterion', 'Reference year start',
       'Reference year end', 'Observation status', 'Confidentiality status',
       'Observation comment', 'Decimals', 'Time period collection',
       'Unit multiplier'],
      dtype='object')

In [57]:
#Identificando onde há dados faltantes:
df_limpo.isna().sum()

STRUCTURE                             0
STRUCTURE_ID                          0
STRUCTURE_NAME                        0
ACTION                                0
Reference area                        0
Education level                       0
Measure                               0
Education type                        0
Intensity                             0
Field of education                    0
Grade                                 0
Frequency of observation              0
Origin                                0
Destination                           0
Type of educational institution       0
Mobility                              0
Unit of measure                       0
Sex                                   0
Age                                   0
Time period                        2700
Observation value                  2700
Reference date for ages            2700
Origin criterion                   2700
Reference year start               2700
Reference year end                 2700
Observation status                    0
Confidentiality status             2700
Observation comment                2700
Decimals                              0
Time period collection             2700
Unit multiplier                       0
dtype: int64

In [59]:
df_limpo = df_limpo.dropna(axis=1)
df_limpo.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'STRUCTURE_NAME', 'ACTION',
       'Reference area', 'Education level', 'Measure', 'Education type',
       'Intensity', 'Field of education', 'Grade', 'Frequency of observation',
       'Origin', 'Destination', 'Type of educational institution', 'Mobility',
       'Unit of measure', 'Sex', 'Age', 'Observation status', 'Decimals',
       'Unit multiplier'],
      dtype='object')

-> Tendo em vista que a maior parte das variáveis tratadas são categóricas, uma forma de padronização seria a transformação do tipo delas em numéricas.