## **Grupo 2: Limpeza e Preparação**

In [20]:
# Grupo 2 Trabalho : Limpeza do datasetDados Nacionais de Segurança Pública - UF
#Importando bibliotecas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display
!git clone https://github.com/claytontey/Aulas_Git-DS.git

fatal: destination path 'Aulas_Git-DS' already exists and is not an empty directory.

In [21]:
caminho_arquivo = './Aulas_Git-DS/TP-1/Giovani_Pablo/dados/indicadoressegurancapublicauf.xlsx'

# Importando a aba de Ocorrências
df_ocorrencias = pd.read_excel(caminho_arquivo, sheet_name='Ocorrências')

# Importando a aba de Vítimas
df_vitimas = pd.read_excel(caminho_arquivo, sheet_name='Vítimas')

# Verificando se a importação deu certo
display(df_ocorrencias.head(2))
display(df_vitimas.head(2))

     UF        Tipo Crime   Ano      Mês  Ocorrências
0  Acre           Estupro  2022  janeiro           31
1  Acre  Furto de veículo  2022  janeiro           50

     UF        Tipo Crime   Ano      Mês Sexo da Vítima  Vítimas
0  Acre  Homicídio doloso  2022  janeiro       Feminino        2
1  Acre  Homicídio doloso  2022  janeiro      Masculino        8

In [22]:
# 1. Verificando os dados nulos;
print("--- DADOS NULOS EM OCORRÊNCIAS ---")
display(df_ocorrencias.isnull().sum())

print("\n--- DADOS NULOS EM VÍTIMAS ---")
display(df_vitimas.isnull().sum())

# 2. Verificando os tipos de dados
print("\n--- TIPOS DE DADOS ---")
print("Ocorrências:\n", df_ocorrencias.dtypes)
print("\nVítimas:\n", df_vitimas.dtypes)

--- DADOS NULOS EM OCORRÊNCIAS ---

UF             0
Tipo Crime     0
Ano            0
Mês            0
Ocorrências    0
dtype: int64

--- DADOS NULOS EM VÍTIMAS ---

UF                0
Tipo Crime        0
Ano               0
Mês               0
Sexo da Vítima    0
Vítimas           0
dtype: int64

--- TIPOS DE DADOS ---
Ocorrências:
 UF             object
Tipo Crime     object
Ano             int64
Mês            object
Ocorrências     int64
dtype: object

Vítimas:
 UF                object
Tipo Crime        object
Ano                int64
Mês               object
Sexo da Vítima    object
Vítimas            int64
dtype: object

In [23]:
# Função para limpar e padronizar colunas de texto
def padronizar_textos(df):
    for coluna in df.columns:
        # Verifica se a coluna é do tipo texto (object)
        if df[coluna].dtype == 'object':
            # 1. Remove espaços em branco no começo e no fim
            df[coluna] = df[coluna].str.strip()
            # 2. Deixa tudo em letras maiúsculas
            df[coluna] = df[coluna].str.upper()
    return df

# Aplicando a padronização nas duas bases
df_ocorrencias = padronizar_textos(df_ocorrencias)
df_vitimas = padronizar_textos(df_vitimas)

In [24]:
# Verificando os valores únicos
print("--- VALORES ÚNICOS: OCORRÊNCIAS ---")
print("UF:", df_ocorrencias['UF'].unique())
print("Tipo Crime:", df_ocorrencias['Tipo Crime'].unique())
print("Mês:", df_ocorrencias['Mês'].unique())

print("\n--- VALORES ÚNICOS: VÍTIMAS ---")
print("Sexo da Vítima:", df_vitimas['Sexo da Vítima'].unique())
#Sem colunas duplicadas ou dados fantasmas

--- VALORES ÚNICOS: OCORRÊNCIAS ---
UF: ['ACRE' 'ALAGOAS' 'AMAPÁ' 'AMAZONAS' 'BAHIA' 'CEARÁ' 'DISTRITO FEDERAL'
 'ESPÍRITO SANTO' 'GOIÁS' 'MARANHÃO' 'MATO GROSSO' 'MATO GROSSO DO SUL'
 'MINAS GERAIS' 'PARÁ' 'PARAÍBA' 'PARANÁ' 'PERNAMBUCO' 'PIAUÍ'
 'RIO DE JANEIRO' 'RIO GRANDE DO NORTE' 'RIO GRANDE DO SUL' 'RONDÔNIA'
 'RORAIMA' 'SANTA CATARINA' 'SÃO PAULO' 'SERGIPE' 'TOCANTINS']
Tipo Crime: ['ESTUPRO' 'FURTO DE VEÍCULO' 'HOMICÍDIO DOLOSO'
 'LESÃO CORPORAL SEGUIDA DE MORTE' 'ROUBO A INSTITUIÇÃO FINANCEIRA'
 'ROUBO DE CARGA' 'ROUBO DE VEÍCULO' 'ROUBO SEGUIDO DE MORTE (LATROCÍNIO)'
 'TENTATIVA DE HOMICÍDIO']
Mês: ['JANEIRO' 'FEVEREIRO' 'MARÇO' 'ABRIL' 'MAIO' 'JUNHO' 'JULHO' 'AGOSTO'
 'SETEMBRO' 'OUTUBRO' 'NOVEMBRO' 'DEZEMBRO']

--- VALORES ÚNICOS: VÍTIMAS ---
Sexo da Vítima: ['FEMININO' 'MASCULINO' 'SEXO NI']

In [25]:
# Verificando se existem linhas 100% idênticas repetidas
duplicadas_ocorrencias = df_ocorrencias.duplicated().sum()
duplicadas_vitimas = df_vitimas.duplicated().sum()

print(f"Linhas duplicadas em Ocorrências: {duplicadas_ocorrencias}")
print(f"Linhas duplicadas em Vítimas: {duplicadas_vitimas}")

Linhas duplicadas em Ocorrências: 0
Linhas duplicadas em Vítimas: 0

In [26]:
# Salvando os dados limpos em novos arquivos CSV
df_ocorrencias.to_csv('ocorrencias_limpo.csv', index=False, encoding='utf-8')
df_vitimas.to_csv('vitimas_limpo.csv', index=False, encoding='utf-8')